In [7]:
import numpy as np 
a = np.array([5,6,9])
a[0]
a.ndim

1

In [8]:
a = np.array([[1,2], [3,4], [5,6]])
a.ndim

2

In [9]:
a.itemsize

8

In [10]:
a.dtype

dtype('int64')

In [11]:
a.shape

(3, 2)

In [13]:
a = np.array([[1,2], [3,4], [5,6]], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
l = range(5)
l

range(0, 5)

In [19]:
np.arange(1,5)

array([1, 2, 3, 4])

In [21]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [23]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [24]:
a = np.array([[1,2], [3,4], [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
a.shape

(3, 2)

In [26]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [28]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [29]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
a.min()

np.int64(1)

In [31]:
a.max()

np.int64(6)

In [32]:
a.sum()

np.int64(21)

In [33]:
a.sum(axis=0)

array([ 9, 12])

In [35]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
a.sum(axis=1)

array([ 3,  7, 11])

In [38]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [39]:
np.std(a)

np.float64(1.707825127659933)

In [40]:
np.median(a)

np.float64(3.5)

In [42]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
a = np.array([[1,2], [3,4], [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
b = np.array([[5,6],[7,8],[8,9]])
b

array([[5, 6],
       [7, 8],
       [8, 9]])

In [53]:
(a+b) 

array([[ 6,  8],
       [10, 12],
       [13, 15]])

In [54]:
a-b

array([[-4, -4],
       [-4, -4],
       [-3, -3]])

In [55]:
a*b

array([[ 5, 12],
       [21, 32],
       [40, 54]])

In [57]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ],
       [0.625     , 0.66666667]])