In [7]:
import numpy as np 
a = np.array([5,6,9])
a[0]
a.ndim

1

In [8]:
a = np.array([[1,2], [3,4], [5,6]])
a.ndim

2

In [9]:
a.itemsize

8

In [10]:
a.dtype

dtype('int64')

In [11]:
a.shape

(3, 2)

In [13]:
a = np.array([[1,2], [3,4], [5,6]], dtype=complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
l = range(5)
l

range(0, 5)

In [19]:
np.arange(1,5)

array([1, 2, 3, 4])

In [21]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [23]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])