In [41]:
import numpy as np

In [42]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [43]:
type(arr1)

numpy.ndarray

In [44]:
arr2 =np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr3 = np.zeros((2, 3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
arr5 =np.eye(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
arr6 = np.identity(3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
# np.arange(start, stop, step)
arr7 = np.arange(5,16,2)
arr7 

array([ 5,  7,  9, 11, 13, 15])

In [50]:
arr8 = np.linspace(0, 25, 10)
arr8

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [51]:
arr9 = np.random.randint(0, 10, (3,3))
arr9

array([[5, 9, 8],
       [6, 6, 7],
       [7, 7, 9]], dtype=int32)

In [52]:
# some important attributes
arr9.shape

(3, 3)

In [53]:
arr2.shape

(3, 3)

In [54]:
arr1.shape

(5,)

In [55]:
arr10 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr10

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [56]:
arr10.shape

(2, 2, 2)

In [57]:
arr10.size

8

In [58]:
arr10.dtype

dtype('int64')

In [59]:
arr10.ndim

3

In [60]:
arr2.ndim

2

In [61]:
arr10.itemsize


8

In [62]:
arr9.astype('float')

array([[5., 9., 8.],
       [6., 6., 7.],
       [7., 7., 9.]])

Numpy array vs Python List.
Numpy array is faster than python list.
Numpy array takes less memory than python list.
Numpy array is more convenient than python list.
Numpy array is more optimized than.
Numpy array is more powerful than python list.

In [63]:
lista = range(100)
# lista
arr11 = np.arange(100)

In [64]:
import sys

In [65]:
print(sys.getsizeof(87)*len(lista))

2800


In [66]:
print(arr11.itemsize*arr11.size)

800


In [67]:
import time

In [68]:
x = range(1000000)
y = range(1000000, 2000000)
start_time = time.time()
c = [(x,y) for x,y in zip(x,y)]
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.5907101631164551 seconds ---


In [70]:
a = np.arange(1000000)
b = np.arange(1000000, 2000000)

start_time = time.time()
c = a + b
print("--- %s seconds ---" % (time.time() - start_time))


--- 0.07676196098327637 seconds ---
