In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
# simple Matrix
matrix = np.array([
    [1,2,3],
    [4,5,6],
])
matrix 

array([[1, 2, 3],
       [4, 5, 6]])

Matrix shape is a tuple storing the number of size of each dimentions. For 2D matrices, the order is always rows-columns.

In [3]:
matrix.shape

(2, 3)

Special Matrices

Identity

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D- Array:",arr1)

# 2D array (Matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2-D Array:",arr2)

# 3D array (Tensor)
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3-D Array:",arr3)


1D- Array: [1 2 3 4 5]
2-D Array: [[1 2 3]
 [4 5 6]]
3-D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
print(type(arr1))      # Type of object
print(arr1.shape)      # Shape of array
print(arr2.shape)
print(arr3.shape)


<class 'numpy.ndarray'>
(5,)
(2, 3)
(2, 2, 2)


In [10]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)  # Element-wise addition
print(a - b)  # Element-wise subtraction
print(a * b)  # Element-wise multiplication
print(a / b)  # Element-wise division
print(a ** 2) # Squaring elements

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[100 400 900]


In [11]:
arr = np.array([1, 2, 3])
print(arr + 10)  # Adds 10 to each element

[11 12 13]


In [12]:
zero_arr = np.zeros((3, 3))  # 3x3 matrix of zeros
print(zero_arr)

ones_arr = np.ones((2, 4))  # 2x4 matrix of ones
print(ones_arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
identity_matrix = np.eye(4)  # 4x4 identity matrix
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
random_arr = np.random.rand(3, 3)  # 3x3 matrix with random values between 0 and 1
print(random_arr)

random_ints = np.random.randint(1, 100, (3, 3))  # 3x3 matrix with random integers between 1 and 100
print(random_ints)


[[0.51759426 0.66981306 0.11919881]
 [0.81639657 0.92793534 0.83772425]
 [0.17868544 0.36625665 0.76090265]]
[[46 29 38]
 [20 14 24]
 [44 82  9]]


In [15]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])   # First element
print(arr[-1])  # Last element


10
50


In [16]:
print(arr[1:4])  # Elements from index 1 to 3
print(arr[:3])   # First 3 elements
print(arr[2:])   # Elements from index 2 to end


[20 30 40]
[10 20 30]
[30 40 50]


In [17]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[1, 1])   # Element at row index 1, column index 1
print(arr2[0, :])   # First row
print(arr2[:, 1])   # Second column


5
[1 2 3]
[2 5 8]


In [18]:
arr = np.array([10, 20, 30, 40, 50])

print(np.mean(arr))   # Mean
print(np.median(arr)) # Median
print(np.std(arr))    # Standard deviation
print(np.var(arr))    # Variance
print(np.min(arr))    # Minimum value
print(np.max(arr))    # Maximum value
print(np.sum(arr))    # Sum of elements
print(np.prod(arr))   # Product of elements


30.0
30.0
14.142135623730951
200.0
10
50
150
12000000


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)  # Reshape into 2 rows, 3 columns
print(reshaped)


[[1 2 3]
 [4 5 6]]


In [20]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))  # Matrix multiplication


[[19 22]
 [43 50]]


In [21]:
print(A.T)  # Transpose of A


[[1 3]
 [2 4]]


In [22]:
print(np.linalg.inv(A))  # Inverse of A


[[-2.   1. ]
 [ 1.5 -0.5]]


In [23]:
print(np.linalg.det(A))  # Determinant of A


-2.0000000000000004


In [24]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])  # Get elements greater than 25


[30 40 50]


In [25]:
unsorted_arr = np.array([3, 1, 4, 1, 5, 9])
sorted_arr = np.sort(unsorted_arr)  # Ascending sort
print(sorted_arr)


[1 1 3 4 5 9]


In [26]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))  # Matrix multiplication


[[19 22]
 [43 50]]


In [27]:
print(A.T)  # Transpose of A


[[1 3]
 [2 4]]


In [28]:
print(np.linalg.inv(A))  # Inverse of A


[[-2.   1. ]
 [ 1.5 -0.5]]


In [29]:
print(np.linalg.det(A))  # Determinant of A


-2.0000000000000004


In [30]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])  # Get elements greater than 25


[30 40 50]
