In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr2 =np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr3 = np.zeros((2, 3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr5 =np.eye(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
arr6 = np.identity(3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# np.arange(start, stop, step)
arr7 = np.arange(5,16,2)
arr7 

array([ 5,  7,  9, 11, 13, 15])

In [15]:
arr8 = np.linspace(0, 25, 10)
arr8

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [16]:
arr9 = np.random.randint(0, 10, (3,3))
arr9

array([[8, 1, 5],
       [3, 8, 7],
       [7, 5, 8]], dtype=int32)

In [18]:
# some important attributes
arr9.shape

(3, 3)

In [19]:
arr2.shape

(3, 3)

In [20]:
arr1.shape

(5,)

In [21]:
arr10 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr10

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
arr10.shape

(2, 2, 2)

In [23]:
arr10.size

8

In [24]:
arr10.dtype

dtype('int64')

In [25]:
arr10.ndim

3

In [26]:
arr2.ndim

2

In [27]:
arr10.itemsize


8

In [28]:
arr9.astype('float')

array([[8., 1., 5.],
       [3., 8., 7.],
       [7., 5., 8.]])