In [2]:
import numpy as np
import numpy.linalg as la

In [4]:
# simple Matrix
matrix = np.array([
    [1,2,3],
    [4,5,6],
])
matrix 

array([[1, 2, 3],
       [4, 5, 6]])

Matrix shape is a tuple storing the number of size of each dimentions. For 2D matrices, the order is always rows-columns.

In [5]:
matrix.shape

(2, 3)

Special Matrices

Identity

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])